# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
# planet = "Earth"
# diameter = 12742

res = "The diameter of {planet} is {diameter}"
print(res.format(planet="Earth",diameter=12742))

The diameter of Earth is 12742


## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [8]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [9]:
import numpy as np

arr = np.zeros(10)

print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
import numpy as np

arr = np.ones(10)*5

print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [13]:
import numpy as np
x=np.arange(20,36)
y=(x%2==0)
print(y)
z=x[y]
print(z)

[ True False  True False  True False  True False  True False  True False
  True False  True False]
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
import numpy as np
arr = np.arange(0,9).reshape((3,3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [17]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [19]:
import pandas as pd


In [20]:
data = [['A', 65], ['B', 66], ['C', 67]]

df = pd.DataFrame(data, columns=['Alphabets', 'ASCII'])

df

Alphabets  ASCII
0         A     65
1         B     66
2         C     67

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [22]:
from pandas.core.window.rolling import timedelta as td
from pandas.io.sql import date as d
import pandas as pd
startDate = d(2023, 1, 1)
endDate = d(2023, 2, 10)
pd.date_range(startDate,endDate-td(days=1),freq='d')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [24]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [25]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns=['Number1','Letters','Number2'])
df

Number1 Letters  Number2
0        1     aaa       22
1        2     bbb       25
2        3     ccc       24