## PyTorch


PyTorch is a Python-based open source and scientific computing package for building neural networks. It is dynamic graph-based framework that allows you to define your neural network in a way that is easy to understand and debug. Today, PyTorch is the [most used deep learning framework](https://paperswithcode.com/trends) and mostly use by researchers and engineers.  


![](./pytorch_most_used.png)


PyTorch support GPU acceleration (making your code run faster) behind the scenes, better than NumPy. PyTorch also provides Autograd for automatic differentiation, which means that your code is automatically differentiated and you can use it to do backpropagation


## Pytoch Installation

Before you installed Pytorch, you need to install the following dependencies: Package Manager (e.g. pip, conda), Python, Numpy. For more information, please refer to the [Pytorch documentation](https://pytorch.org/).

For me, I am using mac and conda as package manager, I therefore  run the following command


## VERIFICATION

To verify your installation works, 


In [2]:
import torch
torch.manual_seed(1234)
torch.__version__

'2.1.0+cu121'

## What is Tensor 

- Assume we have 3 bedrooms, 1 carpark and 2 bathrooms. We can represent this data numerically in a form of vector [3, 1,2] to describe bedrooms, carpark and bathrooms

- Tensor are the standard way of representing data in Pytorch, such as text, images, and audio. Their job is to represent data in a numerical way. 

![](./tensor_represent_data.png)


![](./tensor_loop.png)




## is Tensor all you need? 

- There are many Python Data Structure for holding data including Python List and Numpy Array. List and Numpy Array operations are similar to Pytorch Tensor.
  
- Let us remember the basic of data structures in Python (List and Numpy Array) before we start using Pytorch Tensor


## From Python lists to Numpy Array

 - Python does not have built-in support for Arrays, but Python Lists can be used instead.

 - Using our previous example, we can create a list of Python lists below.


In [4]:
a_list = [3, 1,2] #A list is the Python equivalent of an array

print(a_list) # print the list
print((type(a_list))) # print the type
print(a_list[0]) # subset the list

[3, 1, 2]
<class 'list'>
3


> However, Python lists has the following limitations: It takes large memory size and slow.

- Numpy solved the problems with List: 

  - Size - Numpy data structures take up less space

  - Performance - they have a need for speed and are faster than lists

  - Functionality - SciPy and NumPy have optimized functions such as linear algebra operations built in.


In [6]:
import numpy as np
a_numpy = np.array([1,3,4]) # creating a numpy array
a_numpy

array([1, 3, 4])

In [8]:
type(a_numpy) # nd arrays

numpy.ndarray

In [10]:
a_numpy[0] # we can subset similar to Python list

1

In [12]:
a_numpy.shape # shape of the nd array

(3,)

In [14]:
a_numpy.dtype # dtype of the nd array

dtype('int64')

In [16]:
a_numpy.size # size of the nd array

3

### Performance comparison between Python lists and Numpy Arrays


In [18]:
import numpy as np
import time


size_of_vec = 1000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1


t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

0.00019669532775878906 0.0002002716064453125
Numpy is in this example 0.9821428571428571 faster!


## From Numpy Arrays to Torch Tensor

- Tensors are like arrays, both are data structures that are used to store data. Tensor and Numpy arrays share common operations such as shape and size.

>  Tensors are generalization of vectors and matrices to an arbitrary number of dimensions. 

![](./tensor_generalization.png)


- Similar to how Numpy provides additional support not available in the Python list, so also Tensors provides support not available in Numpy array such as:

  - GPU acceleration , which is a great advantage for deep learning,
  
  - distribute operations on multiple devices or machines,and

  - keep track of the graph of computations that created them ( usefull for backpropagation).
 

## Let us Learn Tensor

Various operations are available on tensors. In the next sections, we will discuss the following operations:

- Creating tensors.
  
- Operations with tensors.
  
- Indexing, slicing, and joining with tensors Computing gradients with tensors.
  
- Using CUDA/MPS tensors with GPUs.


## Creating tensors

- PyTorch allows us to create tensors in many different ways using the torch package. We will discuss some of these ways.

### Creating Random Tensor with a specific size
 
> `torch.tensor` is a general Tensor constructor that infer the data type automatically.


In [20]:
import torch

a_random = torch.tensor((3,4)) # Create a random tensor
print(a_random)

tensor([3, 4])


In [22]:
print(a_random.shape) # print the shape of the random tensor
print(a_random.size()) # print the size of the random tensor
print(type(a_random)) # print the type of the random tensor
print(a_random.type()) # print the type of the random tens

torch.Size([2])
torch.Size([2])
<class 'torch.Tensor'>
torch.LongTensor


> Note: .shape is an alias for .size(), and was added to closely match numpy !

- Intead of allowing the `torch.tensor` to automatically determine the data type, you can explicitly specify the type of the data type by using the `torch.type` parameter 


In [24]:
import torch

a_random = torch.tensor((3,4), dtype= torch.float) # Create a random tensor
print(a_random)

tensor([3., 4.])


In [26]:
print(a_random.shape) # print the shape of the random tensor
print(a_random.size()) # print the size of the random tensor
print(type(a_random)) # print the type of the random tensor
print(a_random.type())

torch.Size([2])
torch.Size([2])
<class 'torch.Tensor'>
torch.FloatTensor


- You can also change an existing tensor type by using the 


In [28]:
a_torch = torch.tensor([1, 2, 3]) 

print(a_torch.type()) # Tensor type

torch.LongTensor


We can change from LongTensor t:


In [30]:
a_short =  a_torch.short() # Convert to short,  
a_float =  a_torch.float() # Convert to float()

print(a_short.type()) # Tensor type
print(a_float.type()) # Tensor type

torch.ShortTensor
torch.FloatTensor


> Note: A variant of `torch.tensor` constructor is `torch.FloatTensor`constructor. When use, the default tensor type is `FloatTensor`. Infact, torch.Tensor is an alias for the `torch.FloatTensor` constructor.

- The following two examples are equivalent:


In [32]:
a_random = torch.Tensor((3,4)) # Create a random tensor
b_random = torch.FloatTensor((3,4)) # Create a random tensor

print(a_random.type())
print(b_random.type())

torch.FloatTensor
torch.FloatTensor


> I would recommend to stick to `torch.tensor`, if you would like to change the type, you can change


 Torch defines 10 tensor types with CPU and GPU variants:
[See different Pytorch Data Types](https://pytorch.org/docs/stable/tensors.html#data-types):

- The most common type (and generally the default) is torch.float32 or torch.float. This is referred to as "32-bit floating point".

- But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

- The reason for all of these is to do with precision in computing. Precision is the amount of detail used to describe a number.

- The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

- This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

> So, lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).


### 2: Creating Tensors from Random Numbers

Similar to the numpy, we can create a tensor from a random number.


In [34]:
a_random_torch = torch.randn(2, 3) # uniform random distribution numbers between 0 and 1
# a_numpy_rand = np.random.randn(2,3) #numpy random normal distribution

print(a_random_torch)
# print(a_numpy_rand)

tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [36]:
a_random_torch = torch.rand(2, 3) # random normal distribution
# a_numpy_rand = np.random.rand(2,3) 

print(a_random_torch)
# print(a_numpy_rand)

tensor([[0.7749, 0.8208, 0.2793],
        [0.6817, 0.2837, 0.6567]])


### 3: Creating a filled tensor


In [38]:
a_same_scalar = torch.zeros(3,3)
print(a_same_scalar)
print(a_same_scalar.size())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [40]:
torch.ones(3, 3) # torch.ones(size=(3, 3)) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

> Any PyTorch method with an underscore (_) refers to an in­place operation;


In [42]:
a_zero = torch.zeros(2, 3)
print(a_zero)
print(a_zero.fill_(5)) # inplace operation
print(a_zero)  # a_zero is now filled with 5

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[5., 5., 5.],
        [5., 5., 5.]])
tensor([[5., 5., 5.],
        [5., 5., 5.]])


###4: Creating and initializing a tensor from lists


In [44]:
a_list = torch.tensor([1, 2, 3])
a_list

tensor([1, 2, 3])

### 5: Creating and initializing a tensor from numpy arrays


- We use `torch.from_numpy` to create a tensor from a numpy array.


In [46]:
import numpy as np
numpy_array = np.random.rand(2, 3) 
numpy_array

torch_tensor = torch.from_numpy(numpy_array) # tensor from numpy array
torch_tensor

tensor([[0.9996, 0.8390, 0.4081],
        [0.4303, 0.7789, 0.5664]], dtype=torch.float64)

In [48]:
torch_tensor.type()

'torch.DoubleTensor'

- The datatype after creating of tensor from numpy array is DoubleTensor instead of the default FloatTensor. This corresponds with the data type of the NumPy random matrix, a `float64`,


> You can always convert from PyTorch tensors to Numpy arrays using the numpy function torch.numpy().


In [50]:
torch_tensor.numpy()

array([[0.99961654, 0.83897727, 0.40814199],
       [0.43029501, 0.77892152, 0.56643743]])

### 6: Creating a range and tensors like


In [52]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten = torch.arange(0, 10) 
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating tensor of type with the same shape as another tensor.


In [54]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Creating Named Tensors

- Named Tensors allow users to give explicit names to tensor dimensions. 

- In most cases, operations that take dimension parameters will accept dimension names, avoiding the need to track dimensions by position.


In [56]:
torch.zeros(2, 3, names=('N', 'C'))

/tmp/ipykernel_21/697701580.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1900.)
  torch.zeros(2, 3, names=('N', 'C'))


tensor([[0., 0., 0.],
        [0., 0., 0.]], names=('N', 'C'))

- We can use `names` to access tensor dimensions.


In [58]:
imgs = torch.randn(1, 2, 2, 3 , names=('N', 'C', 'H', 'W')) 
imgs.names

('N', 'C', 'H', 'W')

In [60]:
imgs.names[0]

'N'

## Tensor properties

Tensor has many properties including the following properties: the number of dimensions, the size, the type: 


### Tensor Dimensions

We can find the tensor dimensions using:`ndim`


In [62]:
# Scalar
scalar = torch.tensor(7)
scalar

scalar.ndim

0

In [64]:
MATRIX = torch.tensor([[1,2,3,4],
                       [5,6,7,8]])

MATRIX.ndim

2

> You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side of the brackets.

In practice, you'll often see scalars and vectors denoted as lowercase letters such as y or a. And matrices and tensors denoted as uppercase letters such as X or W

## Manipulating tensors (tensor operations)

- In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

- A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

- After you have created your tensors, you can operate on them like you would do with traditional programming language types, like +, ­, *, /. 


###  Indexing tensors

Indexing and subsetting a tensor is similar to indexing a list.


In [66]:
some_list = list(range(6))
torch_list = torch.tensor(some_list)
torch_list

tensor([0, 1, 2, 3, 4, 5])

In [68]:
print(torch_list[0]) # first element of the tensor
print(torch_list[1]) # second element of the tensor

tensor(0)
tensor(1)


In [70]:
torch_list[1:4] # subsetting a tensor

tensor([1, 2, 3])

### Transposing Tensors

Transposing 2D tensors is a simple operation using `t`


In [72]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [74]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

You can also transpose 3D and higher tensors using the `transpose` method by specifying the two dimensions along which transposing (flipping shape and stride) should occur:


In [76]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
print(some_t.shape)
print(transpose_t.shape)

torch.Size([3, 4, 5])
torch.Size([5, 4, 3])


###  Tensor View Operation


Tensor view operations returns a new tensor with the same data as the self tensor but of a different shape.


In [78]:
x = torch.randn(2, 2)
print(x)
print(x.size())

tensor([[-0.4790,  0.8539],
        [-0.2285,  0.3081]])
torch.Size([2, 2])


In [80]:
y = x.view(4)
print(y)
print(y.size())

tensor([-0.4790,  0.8539, -0.2285,  0.3081])
torch.Size([4])


>  Using `-1` in the shape argument will automatically infer the correct size of the dimension.


In [82]:
z = x.view(-1, 2)  # the size -1 is inferred from other dimensions

print(z)
print(z.size())

tensor([[-0.4790,  0.8539],
        [-0.2285,  0.3081]])
torch.Size([2, 2])


> View Does not change tensor layout in memory, Transpose() operation change the tensor layout in memory.


### Tensor Mathematical Basic Operations

Tensor addition is achive using `torch.add` as shown in the following example:


In [84]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [86]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [88]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

> PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplcation) and torch.add() to perform basic operations.


In [90]:
# Can also use torch functions
tensor = torch.tensor([1, 2, 3])
torch.multiply(tensor, 10)  # multiply by 10

tensor([10, 20, 30])

In [92]:
tensor = torch.tensor([1, 2, 3])

torch.add(tensor, 20) # add by 20

tensor([21, 22, 23])

In [94]:
torch.div(tensor, 20, rounding_mode='trunc') # divide by 20, with truncation as a rounding_mode

tensor([0, 0, 0])

In [96]:
torch.div(tensor, 20, rounding_mode='floor') # divide by 20, with floor as a rounding_mode

tensor([0, 0, 0])

In [98]:
torch.sum(tensor) # sum tensor entries  [1, 2, 3]

tensor(6)

## Matrix multiplication is all you need

- In deep learning algorithms (like neural networks), one of the most common operations is matrix multiplication.

- PyTorch implements matrix multiplication functionality in the torch.matmul() method.


- The main two rules for matrix multiplication to remember are:

The inner dimensions must match:

  - (3, 2) @ (3, 2) won't work
  - (2, 3) @ (3, 2) will work
  - (3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:

  - (2, 3) @ (3, 2) -> (2, 2)
  - (3, 2) @ (2, 3) -> (3, 3)

Note: "@" in Python is the symbol for matrix multiplication.

More information about matrix multiplication can be found in the [Matrix Multiplication](https://pytorch.org/docs/stable/torch.html#torch-matmul) section.


In [100]:
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)

print(tensor1.shape)
print(tensor2.shape)

torch.Size([3, 4])
torch.Size([4])


In [102]:
result = torch.matmul(tensor1, tensor2)
result.shape

torch.Size([3])

Note: The difference between element-wise multiplication (multiply) and matrix multiplication (matmul) is the addition of values.


- matmul: matrix multiplication
    
- multiply: element-wise multiplication 


In [104]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

Element-wise matrix mutlication


In [106]:
tensor * tensor

tensor([1, 4, 9])

 Matrix multiplication


In [108]:
torch.matmul(tensor, tensor)

tensor(14)

 Can also use the "@" symbol or `torch.mm()` for matrix multiplication, though not recommended


In [110]:
print(tensor @ tensor)
print(tensor.matmul(tensor))

tensor(14)
tensor(14)


> A matrix multiplication like this is also referred to as the dot product of two matrices. Neural networks are full of matrix multiplications and dot products.


For example, [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input `x` and a weights matrix `A`.


$$
y = x\cdot{A^T} + b
$$

Thank you for reading ! 