# NumPy Array Indexing

In [2]:
import numpy as np

## Accessing Array Elements

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
arr[0]

1

In [7]:
arr[2] + arr[3]

7

### Accessing 2-D Arrays

In [9]:
arr1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
print(arr1[0, 1], arr1[1, 4])

2 10


### Accessing 3-D Arrays

In [13]:
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
arr2[0, 1, 2]

6

### Negative Indexing

In [17]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
arr1[1,-1]

10

##  Advanced indexing

### Indexing using index arrays

In [21]:
arr = np.arange(10, 1, -2)
print("\n A sequential array with a negative step: \n",arr)

newarr = arr[np.array([3, 1, 2])]
print("\n Elements at these indices are:\n",newarr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

newarr = arr[np.array([1, 3, -3])]
print("\n Elements are : \n",newarr)


 Elements are : 
 [2 4 7]


### Purely integer indexing

In [25]:
arr = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
print(arr[[0 ,1 ,2 ],[0 ,0 ,1]])

[1 3 6]


### Boolean Indexing 

In [27]:
a = np.array([10, 40, 80, 50, 100])
print(a[a>50])

[ 80 100]


In [29]:
a = np.array([10, 40, 80, 50, 100])
print(a[a%40==0]**2)

[1600 6400]


In [31]:
b = np.array([[5, 5],[4, 5],[16, 4]])
sumrow = b.sum(-1)
# print(sumrow)
print(b[sumrow%10==0])

[[ 5  5]
 [16  4]]
