# Basic Operations in Arrays

In [2]:
import numpy as np

In [3]:
a = np.array([10,20,30,40])
b = np.arange(1,5)

In [4]:
a

array([10, 20, 30, 40])

In [6]:
b

array([1, 2, 3, 4])

In [8]:
a+b

array([11, 22, 33, 44])

In [10]:
a - b

array([ 9, 18, 27, 36])

In [12]:
a * b

array([ 10,  40,  90, 160])

In [14]:
a ** b

array([     10,     400,   27000, 2560000])

In [16]:
#masking
a>15

array([False,  True,  True,  True])

In [18]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [20]:
np.log10(b)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [22]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

#### Matrix Product

In [24]:
A = np.random.randint(0,5, (3,4))
B = np.random.randint(0,5, (4,2))

In [25]:
A

array([[1, 3, 4, 0],
       [0, 4, 0, 2],
       [1, 1, 0, 3]])

In [27]:
B

array([[2, 1],
       [1, 0],
       [0, 1],
       [2, 0]])

In [29]:
np.dot(A,B)

array([[5, 5],
       [8, 0],
       [9, 1]])

# More Operations on Arrays

In [31]:
A = np.arange(0,24)

In [32]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
A = A.reshape(6,4)

In [35]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [39]:
np.sum(A)

276

In [41]:
np.max(A)

23

In [43]:
np.min(A)

0

In [45]:
np.mean(A)

11.5

In [47]:
np.std(A)

6.922186552431729

In [49]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [51]:
np.sum(A, axis=0)

array([60, 66, 72, 78])

In [53]:
np.sum(A, axis=1)

array([ 6, 22, 38, 54, 70, 86])

# Shape manipulation

In [55]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
A.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [61]:
A.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [63]:
np.transpose(A)

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

##### Stacking of Arrays - vstack - hstack

In [65]:
a=np.random.randint(0,10,(2,2))
b=np.random.randint(0,10,(2,2))

In [66]:
a

array([[5, 1],
       [9, 8]])

In [68]:
b

array([[5, 9],
       [0, 5]])

In [70]:
np.hstack((a,b))

array([[5, 1, 5, 9],
       [9, 8, 0, 5]])

In [72]:
np.vstack((a,b))

array([[5, 1],
       [9, 8],
       [5, 9],
       [0, 5]])