# Arithmetic

Arrays allow you to perform stack operations on data without having to use `for` loops. This is called *vectorisation* in NumPy. For all arithmetic operations between arrays of the same size, the operation is applied element by element:

In [2]:
import numpy as np

data = np.random.randn(7, 3)
data

array([[-0.43012546, -0.10796272,  0.05438676],
       [-0.61178552,  0.02731189, -1.17514573],
       [ 1.11775942,  0.71115008, -1.28401564],
       [ 0.54844849, -0.40924022, -0.94977055],
       [ 0.43917948,  0.93350576, -0.3447778 ],
       [-0.32687732,  0.69299648,  0.60578199],
       [-0.53635563,  0.74014226, -0.48190485]])

In [4]:
1 / data

array([[-2.32490308, -9.26245659, 18.38682846],
       [-1.63455977, 36.6140892 , -0.85095829],
       [ 0.8946469 ,  1.40617294, -0.77880671],
       [ 1.82332528, -2.44355258, -1.05288588],
       [ 2.27697344,  1.07123067, -2.90041878],
       [-3.05925172,  1.44300877,  1.65075887],
       [-1.86443463,  1.35109161, -2.07509845]])

In [6]:
data ** 2

array([[1.85007909e-01, 1.16559487e-02, 2.95791951e-03],
       [3.74281522e-01, 7.45939370e-04, 1.38096749e+00],
       [1.24938613e+00, 5.05734436e-01, 1.64869616e+00],
       [3.00795748e-01, 1.67477559e-01, 9.02064093e-01],
       [1.92878612e-01, 8.71432999e-01, 1.18871730e-01],
       [1.06848782e-01, 4.80244121e-01, 3.66971823e-01],
       [2.87677357e-01, 5.47810568e-01, 2.32232282e-01]])

Comparison of two arrays: