# Numpy
- Numpy is fumdamental package for scientific computing in python.It is a python library that provides amulti dimensional arrays, including mathematical, logical, shape, and more.

- At the core of numpy is ndim array which is encapsulates in n-dimentional array of homogeneous data types.

# why numpy array
- Numpy array have a fixed at creation, unlike python list. Channging the size of ndarray will create a new array and delete the original.
- numpy facilate advance mathematical and other operations on large numbers of data.

- numpy has speed of C which is fast data type compare to other python datatype and simple syntax of python

In [2]:
import numpy as np

In [3]:
# create numpy
np.array([1,2,3])

array([1, 2, 3])

In [5]:
a=np.array([1,2,3]) #1D array or vector
type(a)

numpy.ndarray

In [7]:
# 2D And 3D

b = np.array([[1,2,3],[4,5,6]]) # 2D or matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
type(b)

numpy.ndarray

In [11]:
c = np.array([[[1,2,3],[4,5,6,],[7,8,9]]]) # 3D or tensor
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [13]:
# dtype int to float
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [15]:
# dtype int to float
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [17]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# np.arange (alternate)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [21]:
# reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [23]:
# np.ones and np.zeros
np.ones((3,4)) # use to initialized wieghts in neural network 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.random.random((3,4))

array([[0.94544442, 0.27167403, 0.33843556, 0.68197549],
       [0.21603765, 0.13765341, 0.31669686, 0.35392508],
       [0.82388892, 0.80544107, 0.86462166, 0.20649028]])

In [29]:
# np.linspace (linearly space)
np.linspace(-10,10,10) # gives point poin in equal distance

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [31]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [33]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [34]:
print(a1,"\n")
print(a2,"\n")
print(a3)

[0 1 2 3 4 5 6 7 8 9] 

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [36]:
# ndim
a2.ndim # no of items present in data

2

In [38]:
# shape
a1.shape

(10,)

In [40]:
a2.shape

(3, 4)

In [42]:
a3.shape

(2, 2, 2)

In [44]:
# size : no of item
a3.size

8

In [46]:
a2.size

12

In [48]:
# itemsize : in memmory how much
a3.itemsize

8

In [50]:
a2.itemsize

8

In [52]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing Datatype

In [54]:
# astype
a3.dtype

dtype('int64')

In [56]:
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Array Operation

In [58]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [59]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [61]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
# Scalar operation
# arithmatics operation

In [64]:
a1**2 # All arithmatic opertors

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [66]:
# relation operators
a2 >5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [68]:
a2> 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [70]:
# vector operators
# arithmatic operators
a1 + a2 # since same shape

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [72]:
np.min(a2)

12

In [74]:
# max/min/sum/prod
a2.min(), a2.sum(), a1.prod()

(12, 210, 0)

In [76]:
a = np.random.random((3,3))
a = np.round(a*100)
a

array([[30., 65., 83.],
       [87.,  1., 22.],
       [59., 84., 92.]])

In [78]:
# accessing min form all rows
np.max(a,axis=0)

array([87., 84., 92.])

In [80]:
# accessing min form all columns
np.max(a,axis=1)

array([83., 87., 92.])

In [82]:
# mean\median\std\var
a.mean(), np.median(a), a.std(), a.var()

(58.111111111111114, 65.0, 31.049939861972337, 964.0987654320987)

In [84]:
# trigometric function
np.sin(a), np.tanh(a)

(array([[-0.98803162,  0.82682868,  0.96836446],
        [-0.82181784,  0.84147098, -0.00885131],
        [ 0.63673801,  0.73319032, -0.77946607]]),
 array([[1.        , 1.        , 1.        ],
        [1.        , 0.76159416, 1.        ],
        [1.        , 1.        , 1.        ]]))

In [86]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(a2,"\n")
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [88]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [90]:
# log and exponent
np.log(a1)

/tmp/ipykernel_21/2171035234.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [92]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [94]:
# round/floor/ceil

np.round(np.random.random((2,3)))

array([[0., 1., 1.],
       [1., 0., 0.]])

In [96]:
# round/floor/ceil

np.floor(np.random.random((2,3)))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [98]:
# round/floor/ceil

np.ceil(np.random.random((2,3)))

array([[1., 1., 1.],
       [1., 1., 1.]])

# indicing and slicing

In [100]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [101]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [103]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
a1[-1] #last item

9

In [107]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
a2[1,2]

6

In [111]:
a3 # 3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [113]:
a3[1,0,1], a3[0,1,0], a3[0,0,0], a3[1,1,0]

(5, 2, 0, 6)

# slicing

In [115]:
a1[2:5]

array([2, 3, 4])

In [117]:
a1[2:5:2]

array([2, 4])

In [119]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
print(a2[0])
print(a2[1])

[0 1 2 3]
[4 5 6 7]


In [123]:
a2[0,:] # rows

array([0, 1, 2, 3])

In [125]:
a2[:,2] #column

array([ 2,  6, 10])

In [127]:
a2[1:,1:3] # rtectangle

array([[ 5,  6],
       [ 9, 10]])

In [129]:
a2[::2,::3] # acessing vertex of rectangle

array([[ 0,  3],
       [ 8, 11]])

In [131]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [133]:
a2[1,::3]

array([4, 7])

In [135]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

# 3D

In [137]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [139]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [141]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [143]:
a3[0,1,:]

array([3, 4, 5])

In [145]:
a3[1,:,1]

array([10, 13, 16])

In [147]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [149]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# iterating

In [151]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [155]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [157]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [159]:
a2
for i in a2:
    print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [161]:
a3
for i in a3:
    print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [163]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [165]:
# transpose\ravel

In [166]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [168]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [170]:
# ravel: to convert 1d array

In [171]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# stacking

In [173]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [174]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [176]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [178]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# splitting

In [180]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [182]:
# horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [184]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [186]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]