# Numpy 

In [2]:
list = [1,2,3,4]
list1 =[[1,2,3,4],[5,6,7,8]]

In [3]:
import numpy as np                      #For importing numy lib

In [4]:
np.array(list)                          #for creation of array 

array([1, 2, 3, 4])

In [6]:
np.array(list1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

 **<span style='color:green'> This 2 brackets indicates that it is 2d array </span>**

## **<span style='color:blue'> MORE METHOODS FOR ARRAY CREATION </span>**

In [8]:
arr = np.arange(0,10,2)                     #arange methood(start,end,step)
arr

array([0, 2, 4, 6, 8])

In [10]:
arr = np.linspace(0,10,100)                #linspace methhod(start,end,num) 
arr

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [12]:
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [14]:
arr= np.zeros((3,4))                     # zeros methood(nor,noc) use 2 brackets                   
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [18]:
arr = np.ones((3,4))                    #Ones Methhod(nor,noc) use 2 brackets
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
arr = np.eye(5)                        #eye methood(single input) for identity matrix Creation
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
arr = np.random.rand(4)                #rand methood(single num bcoz 1d arry creation)
arr

array([0.34169562, 0.90284016, 0.29863658, 0.81880016])

In [24]:
arr = np.random.rand(4,4)             #rand methood(nor,noc)  coz 2d array creation         
arr

array([[0.62058518, 0.18866229, 0.31766091, 0.35402823],
       [0.89489302, 0.1120847 , 0.04689261, 0.5228511 ],
       [0.54828072, 0.36170744, 0.30922156, 0.48980886],
       [0.89767133, 0.48086007, 0.2166324 , 0.38371773]])

In [26]:
arr = np.random.randn(2)                       #randn Methood(single num coz 1d array Creation)
arr

array([-0.13509357, -1.79848286])

In [28]:
arr = np.random.randn(4,3)                     #randn Methood(nor,noc) 2d array creation
arr

array([[-0.0761001 ,  0.30449063, -0.53064898],
       [ 0.11170579,  1.18734357, -1.39980348],
       [ 0.72819776,  1.05653308, -1.66688693],
       [-0.04114984,  0.88238823,  0.48745672]])

In [30]:
arr = np.random.randint(0,50,10)               #randint Methood(low,high,num)
arr

array([22,  8,  7, 28, 43,  3,  2, 28, 11, 19])

# **<span style='color:blue'> Functions </span>**

In [32]:
arr2 = arr.reshape(5,2)                        #arrname.reshape(nor,noc)                    
arr2

array([[22,  8],
       [ 7, 28],
       [43,  3],
       [ 2, 28],
       [11, 19]])

In [34]:
arr2.max()                                    #arrname.max() gives max element in arr

43

In [36]:
arr2.min()                                    #arrname.min() gives max element in arr

2

In [38]:
arr2.argmax()                                 #arrname.argmax() gives the index where max element in arr                           


4

In [40]:
arr2.argmin()                                #arrname.argmin() gives the index where min element in arr

6

In [42]:
arr2.shape                                   #arrname.shape Gives shape of array

(5, 2)

In [44]:
arr2.dtype                                   #arrname.dtype Gives datatype of array                                   

dtype('int64')

# **<span style='color:blue'> Indexing & Selection </span>**

In [46]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[0]

0

In [50]:
arr[10]

10

In [52]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr [0:5] = 100

In [55]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [57]:
arr2 = arr.copy()                    #arrname.copy() for copying array
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

* 2d Array Slicing

In [59]:
arr = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
arr[0,2]                            #arr[which row,which column]

15

In [63]:
arr[0]                              #arr[which row] for whole row

array([ 5, 10, 15])

In [65]:
arr[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [67]:
arr[0:2,1:]

array([[10, 15],
       [25, 30]])

In [69]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr2 =arr[arr>5]
arr2

array([ 6,  7,  8,  9, 10])

In [73]:
a = arr>5
a

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [75]:
arr[a]

array([ 6,  7,  8,  9, 10])

# Numpy Operations:

In [77]:
arr = np.arange(0,11)        

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [82]:
np.sqrt(arr)     # give square root of array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [84]:
np.exp(arr)      # give exponant of array

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [86]:
np.sin(arr)    #give sin value of arr

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])