# sort()

In [2]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
ran_nums = np.random.randint(1,100,25)
ran_nums

array([ 7, 18, 53,  1, 15, 85, 58, 96, 99, 72, 47, 56, 80, 54, 35,  7, 10,
       33, 57, 91, 70, 29, 97, 36, 79])

## Ascending

In [5]:
np.sort(ran_nums)

array([ 1,  7,  7, 10, 15, 18, 29, 33, 35, 36, 47, 53, 54, 56, 57, 58, 70,
       72, 79, 80, 85, 91, 96, 97, 99])

In [7]:
sorted_ran_nums=sorted(ran_nums,reverse=True)
sorted_ran_nums

[99,
 97,
 96,
 91,
 85,
 80,
 79,
 72,
 70,
 58,
 57,
 56,
 54,
 53,
 47,
 36,
 35,
 33,
 29,
 18,
 15,
 10,
 7,
 7,
 1]

## Descending

In [9]:
np.sort(ran_nums)[::-1]

array([99, 97, 96, 91, 85, 80, 79, 72, 70, 58, 57, 56, 54, 53, 47, 36, 35,
       33, 29, 18, 15, 10,  7,  7,  1])

In [11]:
desc_ran_nums_sorted = np.array(sorted(ran_nums,reverse=True))
desc_ran_nums_sorted

array([99, 97, 96, 91, 85, 80, 79, 72, 70, 58, 57, 56, 54, 53, 47, 36, 35,
       33, 29, 18, 15, 10,  7,  7,  1])

In [13]:
for i in range(len(ran_nums)):
    for j in range(i+1):
        if ran_nums[i]>ran_nums[j]:
            ran_nums[i],ran_nums[j]=ran_nums[j],ran_nums[i]
            
            
ran_nums

array([99, 97, 96, 91, 85, 80, 79, 72, 70, 58, 57, 56, 54, 53, 47, 36, 35,
       33, 29, 18, 15, 10,  7,  7,  1])

In [15]:
x = [16,17,2,5,7]

x= np.array(x)
y = x.argmax()

for i in range(y,len(x)):
    print(x[i])

17
2
5
7


## sorting of matrix

In [17]:
np.sort([2,3,0],axis=-1)

array([0, 2, 3])

### sorting column wise

In [19]:
np.sort([[2,3,0],
         [7,5,8]],axis=1)

array([[0, 2, 3],
       [5, 7, 8]])

In [21]:
np.sort([[2,3,0],
         [7,5,8]],axis=1)

array([[0, 2, 3],
       [5, 7, 8]])

In [23]:
a = np.array([[1,4], 
              [3,1]])
a.sort(axis=1)
print(a)

[[1 4]
 [1 3]]


### sorting row wise

In [25]:
matrix = [[8,3,9],
          [1,5,0]]
np.sort(matrix,axis=0)

array([[1, 3, 0],
       [8, 5, 9]])

In [27]:
a = np.array([[1, 4],[1, 3]])
a.sort(axis=0)
print(a)

[[1 3]
 [1 4]]


# replacing any item in any array using indexing

In [29]:
array = np.array([16,17,2,5,7])
array[1]=100
array

array([ 16, 100,   2,   5,   7])

In [31]:
array = np.array([[21,16,17],
                  [2,5,3],
                  [7,0,8]])
array[0][0]=100
array

array([[100,  16,  17],
       [  2,   5,   3],
       [  7,   0,   8]])

In [33]:
array = np.array([[21,16,17],
                  [2,5,3],
                  [7,0,8]])

array[0:2,0:2]=[[100,200],[300,400]]
array

array([[100, 200,  17],
       [300, 400,   3],
       [  7,   0,   8]])

# Inserting item into Array

In [35]:
array = np.array([16,17,2,5,7])
np.insert(array,1,100)

array([ 16, 100,  17,   2,   5,   7])

In [37]:
array = np.array([16,17,2,5,7])
np.insert(array,-1,1000)

array([  16,   17,    2,    5, 1000,    7])

In [39]:
array = np.array([16,17,2,5,7])
np.insert(array,len(array),1000)

array([  16,   17,    2,    5,    7, 1000])

In [41]:
array = np.array([[21,16,17],
                  [2,5,3],
                  [7,0,8]])
np.insert(array,[0][0],100)

array([100,  21,  16,  17,   2,   5,   3,   7,   0,   8])

# Append()

In [43]:
array = np.array([5,6,7,8])
array

array([5, 6, 7, 8])

In [45]:
np.append(array,10)

array([ 5,  6,  7,  8, 10])

In [47]:
np.append(array,(10,20))

array([ 5,  6,  7,  8, 10, 20])

In [49]:
np.append(array,[10,20])

array([ 5,  6,  7,  8, 10, 20])

In [51]:
array1 = np.array([2,3,4])
array2 = np.array([5,3,4])

array3 = np.append(array1,array2)
array3

array([2, 3, 4, 5, 3, 4])

In [53]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([5,3,4])

np.append(array1,array2)

array([2, 3, 4, 5, 6, 7, 5, 3, 4])

## Appending rowwise in matrix

In [55]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([[5,3,4]])

np.append(array1,array2,axis=0)

array([[2, 3, 4],
       [5, 6, 7],
       [5, 3, 4]])

In [57]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([[5,3,4],
                   [0,0,0]])

np.append(array1,array2,axis=0)

array([[2, 3, 4],
       [5, 6, 7],
       [5, 3, 4],
       [0, 0, 0]])

## Appending column wise in matrix

In [59]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([[5],
                   [0]])

np.append(array1,array2,axis=1)

array([[2, 3, 4, 5],
       [5, 6, 7, 0]])

In [61]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([[5,3,4],
                   [0,0,0]])

np.append(array1,array2,axis=1)

array([[2, 3, 4, 5, 3, 4],
       [5, 6, 7, 0, 0, 0]])

# Concatenate()

In [63]:
array1 = np.array([2,3,4])
array2 = np.array([5,3,4])

final_array = np.concatenate([array1,array2])
final_array

array([2, 3, 4, 5, 3, 4])

In [65]:
array1 = np.array([2,3,4])
array2 = np.array([5,3,4])
array3 = np.array([5,3,9])


final_array = np.concatenate([array1,array2,array3])
final_array

array([2, 3, 4, 5, 3, 4, 5, 3, 9])

In [67]:
array1 = np.array([2,3,4])
array2 = np.array([5,3,4])
array3 = np.array([5,3,9])


final_array = np.concatenate([array1,array2,array3])
final_array.reshape(3,3)

array([[2, 3, 4],
       [5, 3, 4],
       [5, 3, 9]])

## Concatenation along rows in matrix

In [69]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([[5,8,9]])

np.concatenate([array1,array2],axis=0)

array([[2, 3, 4],
       [5, 6, 7],
       [5, 8, 9]])

In [71]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([[5,8,9]])
array3 = np.array([[0,0,0]])

np.concatenate([array1,array2,array3],axis=0)

array([[2, 3, 4],
       [5, 6, 7],
       [5, 8, 9],
       [0, 0, 0]])

## Concatenation along columns in matrix


In [73]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([[5],
                   [0]])

np.concatenate([array1,array2],axis=1)

array([[2, 3, 4, 5],
       [5, 6, 7, 0]])

In [75]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([[5,5],
                   [0,6]])
array3 = np.array([[1],
                   [1]])

con_c_array=np.concatenate([array1,array2,array3],axis=1)
con_c_array

array([[2, 3, 4, 5, 5, 1],
       [5, 6, 7, 0, 6, 1]])

# Looping on array

In [77]:
array1 = np.array([2,3,4,6,7])
for i in array1:
    print(i)

2
3
4
6
7


In [79]:
array1 = np.array([[2,3,4,6,7]])
for i in array1:
    print(i)

[2 3 4 6 7]


In [81]:
array1 = np.array([2,3,4,6,7])
for i in enumerate(array1):
    print(i)

(0, 2)
(1, 3)
(2, 4)
(3, 6)
(4, 7)


In [83]:
array1 = np.array([2,3,4,6,7])
for index,value in enumerate(array1):
    print(index,value)

0 2
1 3
2 4
3 6
4 7


In [85]:
RRR = np.array([[2, 3, 4],
       [5, 6, 7],
       [5, 8, 9],
       [0, 0, 0]])

for i in RRR:
    print(i)
    
print()
for i,v in enumerate(RRR):
    print(i,v)

[2 3 4]
[5 6 7]
[5 8 9]
[0 0 0]

0 [2 3 4]
1 [5 6 7]
2 [5 8 9]
3 [0 0 0]


## np.nditer()

In [87]:
RRR = np.array([[2, 3, 4],
       [5, 6, 7],
       [5, 8, 9],
       [0, 0, 0]])

for i in np.nditer(RRR):
    print(i)

2
3
4
5
6
7
5
8
9
0
0
0


In [89]:
for i in (RRR):
    for j in range(len(i)):print(i[j])

2
3
4
5
6
7
5
8
9
0
0
0


## np.ndenumerate()

In [91]:
display(RRR)
for i,v in np.ndenumerate(RRR):
    print(i,v)

array([[2, 3, 4],
       [5, 6, 7],
       [5, 8, 9],
       [0, 0, 0]])

(0, 0) 2
(0, 1) 3
(0, 2) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(2, 0) 5
(2, 1) 8
(2, 2) 9
(3, 0) 0
(3, 1) 0
(3, 2) 0


In [93]:
# big_brick = 5 * small_bricks
# small_bricks = 1

# area = 12

def wall(big_brick,small_bricks,area=12):
    
    access = big_brick*5 - area
    a=1
    for i in range(5,50,5):
        if access < i:
            big_brick-=a
            break
        a+=1
            
    if big_brick+small_bricks==area:
        return 'wall constructed successfully'
    else:
        return 'please give another combination'

wall(3,2,12)
    

'please give another combination'