# Numpy
- Numpy is fumdamental package for scientific computing in python.It is a python library that provides amulti dimensional arrays, including mathematical, logical, shape, and more.

- At the core of numpy is ndim array which is encapsulates in n-dimentional array of homogeneous data types.

# why numpy array
- Numpy array have a fixed at creation, unlike python list. Channging the size of ndarray will create a new array and delete the original.
- numpy facilate advance mathematical and other operations on large numbers of data.

- numpy has speed of C which is fast data type compare to other python datatype and simple syntax of python

In [1]:
import numpy as np

In [2]:
# create numpy
np.array([1,2,3])

array([1, 2, 3])

In [4]:
a=np.array([1,2,3]) #1D array or vector
type(a)

numpy.ndarray

In [12]:
# 2D And 3D

b = np.array([[1,2,3],[4,5,6]]) # 2D or matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
type(b)

numpy.ndarray

In [14]:
c = np.array([[[1,2,3],[4,5,6,],[7,8,9]]]) # 3D or tensor
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [15]:
# dtype int to float
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [16]:
# dtype int to float
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [18]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# np.arange (alternate)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [21]:
# reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [22]:
# np.ones and np.zeros
np.ones((3,4)) # use to initialized wieghts in neural network 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.random.random((3,4))

array([[0.19634981, 0.83248074, 0.44579501, 0.54674778],
       [0.65589064, 0.70491943, 0.07130629, 0.55244157],
       [0.0354296 , 0.00701826, 0.836591  , 0.97430269]])

In [29]:
# np.linspace (linearly space)
np.linspace(-10,10,10) # gives point poin in equal distance

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [32]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [2]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [40]:
print(a1,"\n")
print(a2,"\n")
print(a3)

[0 1 2 3 4 5 6 7 8 9] 

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [46]:
# ndim
a2.ndim # no of items present in data

2

In [43]:
# shape
a1.shape

(10,)

In [44]:
a2.shape

(3, 4)

In [45]:
a3.shape

(2, 2, 2)

In [47]:
# size : no of item
a3.size

8

In [48]:
a2.size

12

In [49]:
# itemsize : in memmory how much
a3.itemsize

4

In [50]:
a2.itemsize

8

In [5]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing Datatype

In [6]:
# astype
a3.dtype

dtype('int32')

In [7]:
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# Array Operation

In [9]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [10]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
# Scalar operation
# arithmatics operation

In [14]:
a1**2 # All arithmatic opertors

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [16]:
# relation operators
a2 >5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [17]:
a2> 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [18]:
# vector operators
# arithmatic operators
a1 + a2 # since same shape

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [25]:
np.min(a2)

12

In [23]:
# max/min/sum/prod
a2.min(), a2.sum(), a1.prod()

(12, 210, 0)

In [24]:
a = np.random.random((3,3))
a = np.round(a*100)
a

array([[33., 28., 71.],
       [63., 22., 29.],
       [86., 24., 40.]])

In [28]:
# accessing min form all rows
np.max(a,axis=0)

array([86., 28., 71.])

In [30]:
# accessing min form all columns
np.max(a,axis=1)

array([71., 63., 86.])

In [29]:
# mean\median\std\var
a.mean(), np.median(a), a.std(), a.var()

(44.0, 33.0, 22.0, 484.0)

In [32]:
# trigometric function
np.sin(a), np.tanh(a)

(array([[ 0.99991186,  0.27090579,  0.95105465],
        [ 0.1673557 , -0.00885131, -0.66363388],
        [-0.92345845, -0.90557836,  0.74511316]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [35]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(a2,"\n")
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [36]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [38]:
# log and exponent
np.log(a1)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_3928\2171035234.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [39]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [40]:
# round/floor/ceil

np.round(np.random.random((2,3)))

array([[0., 0., 0.],
       [0., 1., 0.]])

In [41]:
# round/floor/ceil

np.floor(np.random.random((2,3)))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# round/floor/ceil

np.ceil(np.random.random((2,3)))

array([[1., 1., 1.],
       [1., 1., 1.]])

# indicing and slicing

In [49]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [50]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [51]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a1[-1] #last item

9

In [53]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
a2[1,2]

6

In [59]:
a3 # 3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
a3[1,0,1], a3[0,1,0], a3[0,0,0], a3[1,1,0]

(5, 2, 0, 6)

# slicing

In [65]:
a1[2:5]

array([2, 3, 4])

In [66]:
a1[2:5:2]

array([2, 4])

In [67]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
print(a2[0])
print(a2[1])

[0 1 2 3]
[4 5 6 7]


In [73]:
a2[0,:] # rows

array([0, 1, 2, 3])

In [74]:
a2[:,2] #column

array([ 2,  6, 10])

In [75]:
a2[1:,1:3] # rtectangle

array([[ 5,  6],
       [ 9, 10]])

In [76]:
a2[::2,::3] # acessing vertex of rectangle

array([[ 0,  3],
       [ 8, 11]])

In [95]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [107]:
a2[1,::3]

array([4, 7])

In [136]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

# 3D

In [139]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [141]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [142]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [144]:
a3[0,1,:]

array([3, 4, 5])

In [147]:
a3[1,:,1]

array([10, 13, 16])

In [148]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [152]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# iterating

In [153]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [155]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [159]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [160]:
a2
for i in a2:
    print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [161]:
a3
for i in a3:
    print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [163]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [164]:
# transpose\ravel

In [165]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [166]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [167]:
# ravel: to convert 1d array

In [168]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# stacking

In [169]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [170]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [171]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [173]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# splitting

In [176]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [181]:
# horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [184]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [185]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]